import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./utilities/navbar";
import Profile from "./utilities/profile";
import Link from "next/link";
import Head from "next/head";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AIDILBAYHAQI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <main>{children}</main>
      </body>
    </html>
  );
}
